version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:rc-alpine
    restart: unless-stopped

  backend:
    image: stepan186/etalon-tex
    restart: unless-stopped
    env_file:
      - ./.env


volumes:
  database: