version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  redis:
    image: redis:rc-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

#  backend:
#    image: 1creator/photostyle.backend
#    restart: unless-stopped
#    build:
#      context: "./backend"


volumes:
  database: